name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: apt install mingw
      run: sudo apt update && sudo apt install -y gcc-mingw-w64-i686
    - uses: actions/checkout@v4
    - name: make
      run: make
    - uses: actions/upload-artifact@v4.6.0
      with:
        name: ffrunner
        path: ffrunner.exe
